# config/packages/nelmio_cors.yaml
nelmio_cors:
    defaults:
        allow_origin: ['*']
        allow_headers: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['http://localhost:4200'] 
            allow_headers: ['Authorization', 'Content-Type']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
